.TH FUYUNIX 6
.SH NAME
fuyunix \- a platformer game
.SH SYNOPSIS
.B fuyunix
.RB [ \-v | -l | -f]
.P
.SH DESCRIPTION
fuyunix is a platformer game with local multiplayer support.
.P
Most of the games now are online multiplayer games where you have to be
connected to the internet. I thought It'll be a good idea to create a game with
local multiplayer just to go against the norms.
.P
This game will still be playable with a single user because I don't have any
friends to play with. It will just support multiplayer on case someone wants
to play with their friend locally.
.SH NOTE
Multiplayer mainly means 2 player support. There might be added support for
more players but I can't confirm it.
.SH OPTIONS
.TP
.B \-v
prints the version number
.TP
.B \-l
prints the list of functions for use in key configuration file. I'm not putting
it in a file because I'll forget to update it.
.TP
.B \-f
launch the game in fullscreen.
.SH ENVIRONMENT VARIABLES
.TP
.B XDG_STATE_HOME
Is used for save states
.TP
.B XDG_CONFIG_HOME
Is used for configurations
.TP
.B HOME
HOME/.fuyunix/ will be used if the XDG environment variables aren't set
.SH FILES
.TP
.I $XDG_STATE_HOME/fuyunix/save
Game save state
.TP
.I $XDG_STATE_HOME/fuyunix/keys.conf
Key configuration file
.P
If the enviroment variables are not set the files will be placed at HOME/.fuyunix/
