.TH FUYUNIX 6
.SH NAME
fuyunix \- a multiplayer platformer
.SH SYNOPSIS
.B fuyunix
.RB [ \-v ]
.P
.SH DESCRIPTION
fuyunix is a platformer game with local multiplayer support
.SH OPTIONS
.RB \-v
prints the version number
.SH BUGS AND ISSUES
This game is still under development so there will be a lot of them.
Open a issue in gtihub or even better send a patch.
