.TH FUYUNIX 6
.SH NAME
fuyunix \- a platformer game
.SH SYNOPSIS
.B fuyunix
.RB [ \-v ]
.P
.SH DESCRIPTION
fuyunix is a platformer game with local multiplayer support.
.P
Most of the games now are online multiplayer games where you have to be
connected to the internet. I thought It'll be a good idea to create a game with
local multiplayer just to go against the norms.
.P
This game will still be playable with a single user because I don't have any
friends to play with. It will just support multiplayer on case someone wants
to play with their friend locally.
.SH NOTE
When I say multiplayer I mainly mean 2 players. There might be support
for more players but I can't confirm it.
.SH OPTIONS
.RB \-v
prints the version number
.SH ENVIRONMENT VARIABLES
.TP
.B XDG_STATE_HOME
Is used for save states
.SH FILES
.TP
.I $XDG_STATE_HOME/fuyunix/save
Game save state
.P
If the enviroment variables are not set the files will go to the default
values.($XDG_STATE_HOME at $HOME/.local/state)
