#include "xdg-decoration-unstable-client-protocol.h"
#include "xdg-shell-client-protocol.h"
#include "xdg-decoration-unstable-protocol.c"
#include "xdg-shell-protocol.c"

#include "src/game.c"
#include "src/platform_wayland.c"
#include "src/scfg.c"
#include "src/util.c"
#include "src/shm.c"
